// ======================================================================
// Project Name    : ios_foundation
//
// Copyright © 2020 U-CREATES. All rights reserved.
//
// This source code is the property of U-CREATES.
// If such findings are accepted at any time.
// We hope the tips and helpful in developing.
// ======================================================================
#import "CubeAsset1.h"
#import "GLESColor.h"
@implementation CubeAsset1
- (id)init:(GLfloat)width height:(GLfloat)height depth:(GLfloat)depth color:(GLESColor*)color {
    self = [super init];
    self->_width = width;
    self->_height = height;
    self->_depth = depth;
    self->_color = color;
    self->_vertex = [[VertexArray alloc] init:3];
    return self;
}
- (void)create {
    GLfloat verticies[] = {
        // front1
        -0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        -0.5f * self->_width,
        -0.5f * self->_height,
        -0.5f * self->_depth,
        // front2
        0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        0.5f * self->_width,
        -0.5f * self->_height,
        -0.5f * self->_depth,
        -0.5f * self->_width,
        -0.5f * self->_height,
        -0.5f * self->_depth,
        // back1
        -0.5f * self->_width,
        0.5f * self->_height,
        0.5f * self->_depth,
        -0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
        0.5f * self->_width,
        0.5f * self->_height,
        0.5f * self->_depth,
        // back2
        0.5f * self->_width,
        0.5f * self->_height,
        0.5f * self->_depth,
        -0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
        0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
        // right1
        0.5f * self->_width,
        0.5f * self->_height,
        0.5f * self->_depth,
        0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
        0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        // right2
        0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
        0.5f * self->_width,
        -0.5f * self->_height,
        -0.5f * self->_depth,
        // left1
        -0.5f * self->_width,
        0.5f * self->_height,
        0.5f * self->_depth,
        -0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        -0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
        // left2
        -0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        -0.5f * self->_width,
        -0.5f * self->_height,
        -0.5f * self->_depth,
        -0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
        // top1
        -0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        -0.5f * self->_width,
        0.5f * self->_height,
        0.5f * self->_depth,
        0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        // top2
        0.5f * self->_width,
        0.5f * self->_height,
        -0.5f * self->_depth,
        -0.5f * self->_width,
        0.5f * self->_height,
        0.5f * self->_depth,
        0.5f * self->_width,
        0.5f * self->_height,
        0.5f * self->_depth,
        // bottom1
        -0.5f * self->_width,
        -0.5f * self->_height,
        -0.5f * self->_depth,
        0.5f * self->_width,
        -0.5f * self->_height,
        -0.5f * self->_depth,
        -0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
        // bottom2
        0.5f * self->_width,
        -0.5f * self->_height,
        -0.5f * self->_depth,
        0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
        -0.5f * self->_width,
        -0.5f * self->_height,
        0.5f * self->_depth,
    };
    GLfloat vertexColors[] = {
        // front
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        // back
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        // left
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        // right
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        // top
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        // bottom
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
        self->_color.r,
        self->_color.g,
        self->_color.b,
        self->_color.a,
    };
    int verticiesLength = sizeof(verticies) / sizeof(GLfloat);
    int vertexColorsLength = sizeof(vertexColors) / sizeof(GLfloat);
    int vertexCount = verticiesLength / self.vertex.dimension;
    [self->_vertex setVertexCount:vertexCount];
    [self->_vertex setVerticies:verticies verticiesCount:verticiesLength];
    [self->_vertex setColors:vertexColors vertexColorsCount:vertexColorsLength];
    [self->_vertex setNormals:verticies verticiesCount:verticiesLength];
    return;
}
- (GLenum)renderMode {
    return GL_TRIANGLES;
}
- (VertexArray*)vertex {
    return self->_vertex;
}
@end
